import "./FormContainer.css";

const FormContainer = () => {
  return (
    <div className="div31">
      <div className="rectangle-parent14">
        <div className="group-child1006" />
        <div className="group-child1007" />
        <div className="group-child1008" />
        <div className="group-child1009" />
        <div className="group-child1010" />
        <div className="group-child1011" />
        <div className="group-child1012" />
        <div className="group-child1013" />
        <div className="group-child1014" />
        <div className="group-child1015" />
        <div className="group-child1016" />
        <div className="group-child1017" />
        <div className="group-child1018" />
        <div className="group-child1019" />
        <div className="group-child1020" />
        <div className="group-child1021" />
        <div className="group-child1022" />
        <div className="group-child1023" />
        <div className="group-child1024" />
        <div className="group-child1025" />
        <div className="group-child1026" />
        <div className="group-child1027" />
        <div className="group-child1028" />
        <div className="group-child1029" />
        <div className="group-child1030" />
        <div className="group-child1031" />
        <div className="group-child1032" />
        <div className="group-child1033" />
        <div className="group-child1034" />
        <div className="group-child1035" />
        <div className="group-child1036" />
        <div className="group-child1037" />
        <div className="group-child1038" />
        <div className="group-child1039" />
        <div className="group-child1040" />
        <div className="group-child1041" />
        <div className="group-child1042" />
        <div className="group-child1043" />
        <div className="group-child1044" />
        <div className="group-child1045" />
        <div className="group-child1046" />
        <div className="group-child1047" />
        <div className="group-child1048" />
        <div className="group-child1049" />
        <div className="group-child1050" />
        <div className="group-child1051" />
        <div className="group-child1052" />
        <div className="group-child1053" />
        <div className="group-child1054" />
        <div className="group-child1055" />
        <div className="group-child1056" />
        <div className="group-child1057" />
        <div className="group-child1058" />
        <div className="group-child1059" />
        <div className="group-child1060" />
        <div className="group-child1061" />
        <div className="group-child1062" />
        <div className="group-child1063" />
        <div className="group-child1064" />
        <div className="group-child1065" />
        <div className="group-child1066" />
        <div className="group-child1067" />
        <div className="group-child1068" />
        <div className="group-child1069" />
        <div className="group-child1070" />
        <div className="group-child1071" />
        <div className="group-child1072" />
        <div className="group-child1073" />
        <div className="group-child1074" />
        <div className="group-child1075" />
        <div className="group-child1076" />
        <div className="group-child1077" />
        <div className="group-child1078" />
        <div className="group-child1079" />
        <div className="group-child1080" />
        <div className="group-child1081" />
        <div className="group-child1082" />
        <div className="group-child1083" />
        <div className="group-child1084" />
        <div className="group-child1085" />
        <div className="group-child1086" />
        <div className="group-child1087" />
        <div className="group-child1088" />
        <div className="group-child1089" />
        <div className="group-child1090" />
        <div className="group-child1091" />
        <div className="group-child1092" />
        <div className="group-child1093" />
        <div className="group-child1094" />
        <div className="group-child1095" />
        <div className="group-child1096" />
        <div className="group-child1097" />
        <div className="group-child1098" />
        <div className="group-child1099" />
        <div className="group-child1100" />
        <div className="group-child1101" />
        <div className="group-child1102" />
        <div className="group-child1103" />
        <div className="group-child1104" />
        <div className="group-child1105" />
        <div className="group-child1106" />
      </div>
      <div className="child687" />
      <div className="child688" />
      <div className="child689" />
      <div className="child690" />
      <div className="child691" />
    </div>
  );
};

export default FormContainer;
